boblocal:
  bucket: wy_wedding
  access_key_id: AKIAJN5C46AGCR4TOQDA
  secret_access_key: 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

development:
  bucket: wy_wedding
  access_key_id: AKIAJN5C46AGCR4TOQDA
  secret_access_key: JwtmvQ1nQWxBUQAaVgVbxrmnaCIu4RwevoOUTie9

test:
  bucket: wyedding
  # access_key_id: AKIAJN5C46AGCR4TOQDA
  # secret_access_key: <your key>

production:
<<<<<<< HEAD
  bucket: ENV['S3_BUCKET']
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']
=======
  bucket: wy_wedding
  access_key_id: AKIAJN5C46AGCR4TOQDA
  secret_access_key: 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
>>>>>>> 48aeeb225cb9ff8085aa78157a2565d36238c9d7
