development:
  bucket: wyedding
  access_key_id: AKIAJN5C46AGCR4TOQDA
  secret_access_key: JwtmvQ1nQWxBUQAaVgVbxrmnaCIu4RwevoOUTie9

test:
  bucket: wyedding
  # access_key_id: AKIAJN5C46AGCR4TOQDA
  # secret_access_key: <your key>

production:
  bucket: wyedding
  access_key_id: AKIAJN5C46AGCR4TOQDA
  secret_access_key: JwtmvQ1nQWxBUQAaVgVbxrmnaCIu4RwevoOUTie9